# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ikube < Formula
  desc "CLI tools to manage your kubeconfig file using infisical !"
  homepage "https://github.com/funkolab/ikube"
  version "0.7.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/funkolab/ikube/releases/download/v0.7.1/ikube_v0.7.1_darwin_amd64.tar.gz"
      sha256 "9f536632d7175f8fd97f2ebaa7fdb5646f62c6c4cc388c88df3279114a5a0e3e"

      define_method(:install) do
        bin.install "ikube"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/funkolab/ikube/releases/download/v0.7.1/ikube_v0.7.1_darwin_arm64.tar.gz"
      sha256 "873d3fbac5f2475ab2d9d8e70331975d955cf6ec33cf8da0c37ea22fddd16e7f"

      define_method(:install) do
        bin.install "ikube"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/funkolab/ikube/releases/download/v0.7.1/ikube_v0.7.1_linux_amd64.tar.gz"
      sha256 "32f3296536e7f67fc2df0b107d75e6eb6013613b154bb85d084956526aa8089e"
      define_method(:install) do
        bin.install "ikube"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/funkolab/ikube/releases/download/v0.7.1/ikube_v0.7.1_linux_arm64.tar.gz"
      sha256 "4eec2f3361dbe9496ef3a8c5652422ccf2b6b3dcffa5b89896fbad794c75dc08"
      define_method(:install) do
        bin.install "ikube"
      end
    end
  end

  test do
    system "ikube -h"
  end
end
