# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kube < Formula
  desc "CLI tools to manage your kubeconfig file !"
  homepage "https://github.com/funkolab/kube"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/funkolab/kube/releases/download/v0.1.0/kube_v0.1.0_darwin_amd64.tar.gz"
      sha256 "b5a54712818253bb596dc9588a3708b30480f32b840a5b51d025b0dd3b33d6f4"

      def install
        bin.install "kube"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/funkolab/kube/releases/download/v0.1.0/kube_v0.1.0_darwin_arm64.tar.gz"
      sha256 "d5498e07e4d37c41e97b67568e14a0ff84f4434c7df6df413bd592aec0c95e4e"

      def install
        bin.install "kube"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/funkolab/kube/releases/download/v0.1.0/kube_v0.1.0_linux_arm64.tar.gz"
      sha256 "7879b8330d82ec88b520f38264cfdd915612e0d55cd7af8a4f9077b60637cd6e"

      def install
        bin.install "kube"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/funkolab/kube/releases/download/v0.1.0/kube_v0.1.0_linux_amd64.tar.gz"
      sha256 "99fcde905d0dd528032f58f832587380b4ad07e615105bc6fc637357fd27d088"

      def install
        bin.install "kube"
      end
    end
  end

  test do
    system "kube -h"
  end
end
