# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kube < Formula
  desc "CLI tools to manage your kubeconfig file !"
  homepage "https://github.com/funkolab/kube"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/funkolab/kube/releases/download/v0.4.0/kube_v0.4.0_darwin_arm64.tar.gz"
      sha256 "f32bfe0954bf468e1c5ea830dc771ff5b55cb957821796ced08930d18dfedf01"

      def install
        bin.install "kube"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/funkolab/kube/releases/download/v0.4.0/kube_v0.4.0_darwin_amd64.tar.gz"
      sha256 "77072bc8e8f0e4e10f915a9754fe303a232a365067ee188a4bc86ee32a6e422f"

      def install
        bin.install "kube"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/funkolab/kube/releases/download/v0.4.0/kube_v0.4.0_linux_amd64.tar.gz"
      sha256 "a7d570e9149e8e181c00d998762afda8d728eced8b32d289e16f338af3c64aaa"

      def install
        bin.install "kube"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/funkolab/kube/releases/download/v0.4.0/kube_v0.4.0_linux_arm64.tar.gz"
      sha256 "a87ccb013bcafa1cb4edb3522d31bc1807eec5fea603610f7e5114dece41e955"

      def install
        bin.install "kube"
      end
    end
  end

  test do
    system "kube -h"
  end
end
